### ISSUE TITLE
code not running properly for upload.py 

### ISSUE THREAD

**Issue by Surjitsarkar** [tsyogesh40/Humanrex_CodeIgniter#14]
It just take "name"  as input ---> in inital state then it looks like it goes to "infinite loop" or something but doesn't take any other input.... just go to the next line 
![doubt1](https://user-images.githubusercontent.com/62298893/76874477-3f525e80-6895-11ea-8808-96c7345b1022.JPG)
 
Extra Info:
----> I am using Mantra MFS100 device as scanner.

**Comment by tsyogesh40** [comment]
Code is working fine. 
Ensure your serial communication port  in case of windows

 serial.Serial('/dev/ttyUSB0',57600,timeout=1)     
Don't forgot to setup ur DB
